-- Complète le schéma historique avec les champs utilisés par les entités JPA
-- du flux d'engagement, liquidation, mandat, paiement et régularisation.
ALTER TABLE engagements
    ADD COLUMN IF NOT EXISTS contrat_service_id UUID,
    ADD COLUMN IF NOT EXISTS controller_financier_visa_id UUID,
    ADD COLUMN IF NOT EXISTS credits_reserves BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS date_visa TIMESTAMP,
    ADD COLUMN IF NOT EXISTS depassement_credit_autorise BOOLEAN,
    ADD COLUMN IF NOT EXISTS documentm5id UUID,
    ADD COLUMN IF NOT EXISTS etat VARCHAR(255),
    ADD COLUMN IF NOT EXISTS lignebudgetaire_id UUID,
    ADD COLUMN IF NOT EXISTS montantht NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS montant_impot NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS montantttc NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS montanttva NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS motif_rejet VARCHAR(255),
    ADD COLUMN IF NOT EXISTS numero_engagement VARCHAR(255),
    ADD COLUMN IF NOT EXISTS ordonnator_id UUID,
    ADD COLUMN IF NOT EXISTS periodicite VARCHAR(255),
    ADD COLUMN IF NOT EXISTS taux_impot NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS tauxtva NUMERIC(19,2);

ALTER TABLE liquidations
    ADD COLUMN IF NOT EXISTS agent_service_fait_id UUID,
    ADD COLUMN IF NOT EXISTS attestation_fiscale_presente BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS controller_financier_validation_id UUID,
    ADD COLUMN IF NOT EXISTS date_atestation_service_fait TIMESTAMP,
    ADD COLUMN IF NOT EXISTS date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS date_validation TIMESTAMP,
    ADD COLUMN IF NOT EXISTS detail_prestations VARCHAR(255),
    ADD COLUMN IF NOT EXISTS ecart_regularise NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS etat VARCHAR(255),
    ADD COLUMN IF NOT EXISTS montanthtliquide NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS montant_impot_retenue NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS montantnap NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS montantttcliquide NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS montanttvaliquide NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS numero_liquidation_originale VARCHAR(255),
    ADD COLUMN IF NOT EXISTS ordonnator_id UUID,
    ADD COLUMN IF NOT EXISTS service_fait_ateste BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS taux_impot_retenue NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS tauxtva NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS url_attestation_fiscale VARCHAR(255),
    ADD COLUMN IF NOT EXISTS url_facture VARCHAR(255);

ALTER TABLE mandats
    ADD COLUMN IF NOT EXISTS controller_financier_visa_id UUID,
    ADD COLUMN IF NOT EXISTS cosignataider_id UUID,
    ADD COLUMN IF NOT EXISTS date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS date_mandat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS date_paiement TIMESTAMP,
    ADD COLUMN IF NOT EXISTS date_soumissioncf TIMESTAMP,
    ADD COLUMN IF NOT EXISTS date_transmission_receveur TIMESTAMP,
    ADD COLUMN IF NOT EXISTS date_valicf TIMESTAMP,
    ADD COLUMN IF NOT EXISTS depense_validee_signal BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS etat VARCHAR(255),
    ADD COLUMN IF NOT EXISTS etat_paiement VARCHAR(255),
    ADD COLUMN IF NOT EXISTS mode_paiement VARCHAR(255),
    ADD COLUMN IF NOT EXISTS montantnap NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS montant_retenu_source NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS montantttcmandate NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS numero_check_paiement VARCHAR(255),
    ADD COLUMN IF NOT EXISTS numero_mandat VARCHAR(255),
    ADD COLUMN IF NOT EXISTS ordonnator_id UUID,
    ADD COLUMN IF NOT EXISTS periode_versement VARCHAR(255),
    ADD COLUMN IF NOT EXISTS receve_id UUID,
    ADD COLUMN IF NOT EXISTS url_bordereau_mandats VARCHAR(255),
    ADD COLUMN IF NOT EXISTS url_liasse_documents VARCHAR(255),
    ADD COLUMN IF NOT EXISTS engagement_id UUID;

ALTER TABLE paiements
    ADD COLUMN IF NOT EXISTS cachet_vu_bonapayer BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS cosignataider_id UUID,
    ADD COLUMN IF NOT EXISTS date_apposition_cachet TIMESTAMP,
    ADD COLUMN IF NOT EXISTS date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS date_paiement TIMESTAMP,
    ADD COLUMN IF NOT EXISTS date_programmation_paiement TIMESTAMP,
    ADD COLUMN IF NOT EXISTS date_reception_mandat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS date_signature_cosignataire TIMESTAMP,
    ADD COLUMN IF NOT EXISTS date_signature_receveur TIMESTAMP,
    ADD COLUMN IF NOT EXISTS disponibilites_banque NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS disponibilites_caisse NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS disponibilites_suffisantes BOOLEAN,
    ADD COLUMN IF NOT EXISTS etat VARCHAR(255),
    ADD COLUMN IF NOT EXISTS justification_differement VARCHAR(255),
    ADD COLUMN IF NOT EXISTS montantnapverse NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS montant_retenu_source NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS montantttcpaye NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS motif_echec VARCHAR(255),
    ADD COLUMN IF NOT EXISTS numero_cheque VARCHAR(255),
    ADD COLUMN IF NOT EXISTS oppositions_verifiees BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS ordre_virement_genere VARCHAR(255),
    ADD COLUMN IF NOT EXISTS prescription_verifiee BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS receve_id UUID,
    ADD COLUMN IF NOT EXISTS redevabilite_verifiee BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS signature_cosignatire_effectuee BOOLEAN,
    ADD COLUMN IF NOT EXISTS signature_receve_effectuee BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS validit_creance_verifiee BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE regularisations_470xx
    ADD COLUMN IF NOT EXISTS alertej15declenchee BOOLEAN,
    ADD COLUMN IF NOT EXISTS alertej25declenchee BOOLEAN,
    ADD COLUMN IF NOT EXISTS contrepassation470xxautoeffectuee BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS controller_financier_visa_id UUID,
    ADD COLUMN IF NOT EXISTS date_visacf TIMESTAMP,
    ADD COLUMN IF NOT EXISTS delai_visacf INTEGER,
    ADD COLUMN IF NOT EXISTS motif_rejetcf VARCHAR(255),
    ADD COLUMN IF NOT EXISTS nature_dépense VARCHAR(255),
    ADD COLUMN IF NOT EXISTS notification_tutelle_envoyee BOOLEAN,
    ADD COLUMN IF NOT EXISTS ordonnator_id UUID,
    ADD COLUMN IF NOT EXISTS ordonnator_notifie BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS receve_id UUID;

CREATE TABLE IF NOT EXISTS ligne_mandat (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    compte_comptable_tiers VARCHAR(255),
    montantnap NUMERIC(19,2) NOT NULL,
    montantttc NUMERIC(19,2) NOT NULL,
    numero_ligne INTEGER NOT NULL,
    tiers_beneficiaire VARCHAR(255) NOT NULL,
    tiers_id VARCHAR(255) NOT NULL,
    liquidation_id UUID NOT NULL,
    mandat_id UUID NOT NULL
);
